server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weishop?characterEncoding=utf-8&serverTimezone=GMT%2B8
#    jdbc:mysql://localhost:3306/student?serverTimezone=CTT&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;allowMultiQueries=true
    username: root
    password: 855420
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true