server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weishop?characterEncoding=utf-8&serverTimezone=GMT%2B8
#    jdbc:mysql://localhost:3306/student?serverTimezone=CTT&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;allowMultiQueries=true
    username: root
    password: 855420
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true


shop3:
  security:
    jwt-key: ccccheng
    token-expired-in: 8640000
  order:
    max-sku-limit: 777
    pay-time-limit: 3600
    pay-callback-host: http://talein.com
    pay-callback-path: /v1/payment/wx/notify


